const defaultDoses=[{time:'6:00 AM',name:'Levodopa',amount:'½ tablet',status:'taken'},{time:'10:00 AM',name:'Levodopa',amount:'½ tablet',status:'due'},{time:'2:00 PM',name:'Levodopa',amount:'½ tablet',status:'due'},{time:'6:00 PM',name:'Levodopa CR',amount:'1 tablet',status:'due'},{time:'9:00 PM',name:'Kinetica',amount:'8 mg',status:'due'}];
let doses=JSON.parse(localStorage.getItem('sd-doses')||'null')||defaultDoses,journal=JSON.parse(localStorage.getItem('sd-journal')||'[]'),tab='today',previous=null;
const screen=document.querySelector('#screen'),toast=document.querySelector('#toast');
const save=()=>{localStorage.setItem('sd-doses',JSON.stringify(doses));localStorage.setItem('sd-journal',JSON.stringify(journal))};
function notify(text,undo=false){toast.innerHTML=`<span>${text}</span>${undo?'<button id="undo">UNDO</button>':''}`;toast.classList.add('show');if(undo)document.querySelector('#undo').onclick=()=>{doses=previous;save();render();notify('Action undone')};setTimeout(()=>toast.classList.remove('show'),4500)}
function take(i,status='taken'){previous=structuredClone(doses);doses[i].status=status;save();render();notify(`Dose marked ${status}`,true)}
function check(state){journal.unshift({state,time:new Date().toLocaleTimeString([],{hour:'numeric',minute:'2-digit'})});save();render();notify(`${state} state saved`)}
const stateButtons=()=>`<div class="states">${[['ON','●','Moving well'],['OFF','◐','Symptoms returned'],['Dyskinesia','≈','Extra movement'],['Freezing','❄','Hard to move']].map(x=>`<button onclick="check('${x[0]}')"><b>${x[1]}</b><strong>${x[0]}</strong><small>${x[2]}</small></button>`).join('')}</div>`;
function today(){let i=doses.findIndex(d=>d.status==='due'),taken=doses.filter(d=>['taken','late'].includes(d.status)).length,pct=Math.round(taken/doses.length*100),d=doses[i];return `<div class="intro"><small>${new Date().toLocaleDateString('en-PH',{weekday:'long',month:'long',day:'numeric'})}</small><h1>Good day, Kimmy</h1><p>One dose at a time. You’re doing well.</p></div><section class="next"><small>NEXT DOSE</small><h2>${d?d.time:'All done'}</h2>${d?`<div class="med"><b>●</b><div><strong>${d.name}</strong><span>${d.amount}</span></div></div><button class="take" onclick="take(${i})">✓ I TOOK MY DOSE</button><div class="twins"><button onclick="take(${i},'late')">Taken late</button><button onclick="take(${i},'skipped')">Skip dose</button></div>`:'<p>You completed today’s schedule.</p>'}</section><h3>How are you moving?</h3>${stateButtons()}<section class="progress"><b>${pct}%</b><div><small>TODAY’S PROGRESS</small><strong>${taken} of ${doses.length} doses taken</strong><span>${journal.length} symptom check-ins recorded</span></div></section>`}
function schedule(){return `<div class="title"><small>MEDICATION PLAN</small><h1>Today’s schedule</h1><p>Tap Take to update a dose.</p></div><div class="dose-list">${doses.map((d,i)=>`<article class="${d.status}"><b>${d.time}</b><div><strong>${d.name}</strong><small>${d.amount}</small></div><em>${d.status==='taken'?'✓ Taken':d.status}</em>${d.status==='due'?`<button onclick="take(${i})">Take</button>`:''}</article>`).join('')}</div><section class="refill"><div><small>REFILL STATUS</small><strong>Levodopa</strong><span>24 tablets remaining · about 12 days</span></div><b>Supply good</b></section>`}
function journalView(){return `<div class="title"><small>SYMPTOM JOURNAL</small><h1>How are you feeling?</h1><p>Your entry is timestamped automatically.</p></div>${stateButtons()}<h3>Recent entries</h3>${journal.length?`<div class="timeline">${journal.map(j=>`<article><b>●</b><div><strong>${j.state}</strong><small>${j.time}</small></div></article>`).join('')}</div>`:'<div class="empty">♡<strong>No check-ins yet today.</strong><span>Use the buttons above when your movement changes.</span></div>'}`}
function care(){let taken=doses.filter(d=>['taken','late'].includes(d.status)).length,pct=Math.round(taken/doses.length*100),missed=doses.filter(d=>d.status==='skipped').length;return `<div class="title"><small>CARE CIRCLE</small><h1>Today at a glance</h1><p>A calm summary for Kimmy and her caregivers.</p></div><div class="summary"><div><b>${pct}%</b><small>Dose adherence</small></div><div><b>${missed}</b><small>Missed doses</small></div><div><b>${journal.length}</b><small>Check-ins</small></div></div><section class="care"><i>JD</i><div><small>LINKED CAREGIVER</small><strong>Jasmin Daria</strong><span>Can view adherence and assist with reminders.</span></div><b>Connected</b></section><button class="report" onclick="print()">▣ CREATE DOCTOR REPORT</button><p class="privacy">🔒 Kimmy controls what is shared. Caregiver changes are always visible.</p>`}
function render(){screen.innerHTML=tab==='today'?today():tab==='schedule'?schedule():tab==='journal'?journalView():care()}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));render()});render();
